const nodemailer = require("nodemailer");

const sendGeneratedPassword = async (email, password) => {
  try {
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS,
      },
      tls: {
        rejectUnauthorized: false,
      },
    });

    const mailOptions = {
      from: `"Bloggin'" <${process.env.MAIL_USER}>`,
      to: email,
      subject: "Welcome to Bloggin' – Your Account Password 🔑",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #eee; padding: 20px; border-radius: 10px; background-color: #f9f9f9;">
          <h2 style="color: #333;">Welcome to Bloggin'! 🎉</h2>
          <p style="font-size: 16px; color: #555;">
            Your account has been successfully created using Google Sign-In. 
            We've generated a password for you so that you can also log in directly using your email and password.
          </p>
          <div style="text-align: center; margin: 20px 0;">
            <span style="display: inline-block; font-size: 28px; font-weight: bold; color: #2b6cb0; background: #e6f0ff; padding: 10px 20px; border-radius: 8px;">
              ${password}
            </span>
          </div>
          <p style="font-size: 14px; color: #777;">
            This password was generated by the Bloggin' Team. 
            For your security, we highly recommend that you change it immediately in your 
            <strong>Profile Settings</strong>.
          </p>
          <p style="font-size: 14px; color: #999;">
            Thank you for joining us and happy blogging! ✍️
          </p>
          <hr style="margin: 20px 0; border: none; border-top: 1px solid #eee;">
          <p style="font-size: 14px; color: #aaa;">
            — The Bloggin' Team
          </p>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
  } catch (err) {
    console.error("❌ Failed to send welcome email:", err);
    throw err;
  }
};

module.exports =  sendGeneratedPassword;
